In [133]:
import pandas as pd
from QuantLab.utils.config import load_pathes
from pathlib import Path
from datetime import date

In [134]:
folder = load_pathes()["data"]

In [135]:
panel_path = folder/"raw"/"2000_2026"/"ETF V01.xlsx"
spy_path = folder/"raw"/"2000_2026"/"SPY_2020.xlsx"

In [136]:
panel = pd.read_excel(panel_path)
spy = pd.read_excel(spy_path)

In [137]:
panel.head()

,Start Date,2000-01-01 00:00:00,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113
0,End Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,XLB US Equity,NaN,NaN,NaN,NaN,NaN,XLC US Equity,NaN,NaN,...,NaN,NaN,NaN,NaN,FDTR Index,NaN,CPI YOY Index,NaN,USURTOT Index,NaN
3,NaN,Last Price,Open Price,High Price,Low Price,Volume,Total Return Index (Gross Dividends),Last Price,Open Price,High Price,...,Open Price,High Price,Low Price,Total Return Index (Gross Dividends),Last Price,Total Return Index (Gross Dividends),Last Price,Total Return Index (Gross Dividends),Last Price,Total Return Index (Gross Dividends)
4,Dates,PX_LAST,PX_OPEN,PX_HIGH,PX_LOW,PX_VOLUME,TOT_RETURN_INDEX_GROSS_DVDS,PX_LAST,PX_OPEN,PX_HIGH,...,PX_OPEN,PX_HIGH,PX_LOW,TOT_RETURN_INDEX_GROSS_DVDS,PX_LAST,TOT_RETURN_INDEX_GROSS_DVDS,PX_LAST,TOT_RETURN_INDEX_GROSS_DVDS,PX_LAST,TOT_RETURN_INDEX_GROSS_DVDS

In [138]:
panel.iloc[2,:] = panel.iloc[2,:].ffill()

In [139]:
name = panel.iloc[2,:].fillna('')
cat = panel.iloc[4,:]
columns = [(i+' '+j).strip() for i,j in zip(name,cat)]

In [140]:
columns

['Dates',
 'XLB US Equity PX_LAST',
 'XLB US Equity PX_OPEN',
 'XLB US Equity PX_HIGH',
 'XLB US Equity PX_LOW',
 'XLB US Equity PX_VOLUME',
 'XLB US Equity TOT_RETURN_INDEX_GROSS_DVDS',
 'XLC US Equity PX_LAST',
 'XLC US Equity PX_OPEN',
 'XLC US Equity PX_HIGH',
 'XLC US Equity PX_LOW',
 'XLC US Equity PX_VOLUME',
 'XLC US Equity TOT_RETURN_INDEX_GROSS_DVDS',
 'XLE US Equity PX_LAST',
 'XLE US Equity PX_OPEN',
 'XLE US Equity PX_HIGH',
 'XLE US Equity PX_LOW',
 'XLE US Equity PX_VOLUME',
 'XLE US Equity TOT_RETURN_INDEX_GROSS_DVDS',
 'XLF US Equity PX_LAST',
 'XLF US Equity PX_OPEN',
 'XLF US Equity PX_HIGH',
 'XLF US Equity PX_LOW',
 'XLF US Equity PX_VOLUME',
 'XLF US Equity TOT_RETURN_INDEX_GROSS_DVDS',
 'XLI US Equity PX_LAST',
 'XLI US Equity PX_OPEN',
 'XLI US Equity PX_HIGH',
 'XLI US Equity PX_LOW',
 'XLI US Equity PX_VOLUME',
 'XLI US Equity TOT_RETURN_INDEX_GROSS_DVDS',
 'XLK US Equity PX_LAST',
 'XLK US Equity PX_OPEN',
 'XLK US Equity PX_HIGH',
 'XLK US Equity PX_LOW',
 'XLK US Equity PX_VOLUME',
 'XLK US Equity TOT_RETURN_INDEX_GROSS_DVDS',
 'XLP US Equity PX_LAST',
 'XLP US Equity PX_OPEN',
 'XLP US Equity PX_HIGH',
 'XLP US Equity PX_LOW',
 'XLP US Equity PX_VOLUME',
 'XLP US Equity TOT_RETURN_INDEX_GROSS_DVDS',
 'XLU US Equity PX_LAST',
 'XLU US Equity PX_OPEN',
 'XLU US Equity PX_HIGH',
 'XLU US Equity PX_LOW',
 'XLU US Equity PX_VOLUME',
 'XLU US Equity TOT_RETURN_INDEX_GROSS_DVDS',
 'XLV US Equity PX_LAST',
 'XLV US Equity PX_OPEN',
 'XLV US Equity PX_HIGH',
 'XLV US Equity PX_LOW',
 'XLV US Equity PX_VOLUME',
 'XLV US Equity TOT_RETURN_INDEX_GROSS_DVDS',
 'XLRE US Equity PX_LAST',
 'XLRE US Equity PX_OPEN',
 'XLRE US Equity PX_HIGH',
 'XLRE US Equity PX_LOW',
 'XLRE US Equity PX_VOLUME',
 'XLRE US Equity TOT_RETURN_INDEX_GROSS_DVDS',
 'XLY US Equity PX_LAST',
 'XLY US Equity PX_OPEN',
 'XLY US Equity PX_HIGH',
 'XLY US Equity PX_LOW',
 'XLY US Equity PX_VOLUME',
 'XLY US Equity TOT_RETURN_INDEX_GROSS_DVDS',
 'SPX Index PX_LAST',
 'SPX Index PX_OPEN',
 'SPX Index PX_HIGH',
 'SPX Index PX_LOW',
 'SPX Index PX_VOLUME',
 'SPX Index TOT_RETURN_INDEX_GROSS_DVDS',
 'VIX Index PX_LAST',
 'VIX Index PX_OPEN',
 'VIX Index PX_HIGH',
 'VIX Index PX_LOW',
 'VIX Index TOT_RETURN_INDEX_GROSS_DVDS',
 'USGG10YR Index PX_LAST',
 'USGG10YR Index PX_OPEN',
 'USGG10YR Index PX_HIGH',
 'USGG10YR Index PX_LOW',
 'USGG10YR Index TOT_RETURN_INDEX_GROSS_DVDS',
 'USGG2YR Index PX_LAST',
 'USGG2YR Index PX_OPEN',
 'USGG2YR Index PX_HIGH',
 'USGG2YR Index PX_LOW',
 'USGG2YR Index TOT_RETURN_INDEX_GROSS_DVDS',
 'FDTR Index PX_LAST',
 'CPI YOY Index PX_LAST',
 'CPI YOY Index TOT_RETURN_INDEX_GROSS_DVDS',
 'USURTOT Index PX_LAST',
 'USURTOT Index TOT_RETURN_INDEX_GROSS_DVDS',
 'VIX Index PX_LAST',
 'VIX Index PX_OPEN',
 'VIX Index PX_HIGH',
 'VIX Index PX_LOW',
 'VIX Index TOT_RETURN_INDEX_GROSS_DVDS',
 'USGG10YR Index PX_LAST',
 'USGG10YR Index PX_OPEN',
 'USGG10YR Index PX_HIGH',
 'USGG10YR Index PX_LOW',
 'USGG10YR Index TOT_RETURN_INDEX_GROSS_DVDS',
 'USGG2YR Index PX_LAST',
 'USGG2YR Index PX_OPEN',
 'USGG2YR Index PX_HIGH',
 'USGG2YR Index PX_LOW',
 'USGG2YR Index TOT_RETURN_INDEX_GROSS_DVDS',
 'FDTR Index PX_LAST',
 'FDTR Index TOT_RETURN_INDEX_GROSS_DVDS',
 'CPI YOY Index PX_LAST',
 'CPI YOY Index TOT_RETURN_INDEX_GROSS_DVDS',
 'USURTOT Index PX_LAST',
 'USURTOT Index TOT_RETURN_INDEX_GROSS_DVDS']

In [141]:
panel = panel.iloc[5:,:]
panel.columns = columns

In [142]:
# panel.index = panel["Dates"]

In [143]:
spy.head()

,Start Date,2020-01-01 00:00:00,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,End Date,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,SPY US Equity,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dates,PX_LAST,PX_OPEN,PX_HIGH,PX_LOW,PX_VOLUME,TOT_RETURN_INDEX_GROSS_DVDS

In [144]:
spy.iloc[2,:] = spy.iloc[2,:].ffill()

In [145]:
name = spy.iloc[2,:].fillna('')
cat = spy.iloc[4,:]
columns = [(i+' '+j).strip() for i,j in zip(name,cat)]

In [146]:
spy = spy.iloc[5:,:]
spy.columns = columns

In [147]:
# spy.index = spy["Dates"]

In [148]:
spy.head()

,Dates,SPY US Equity PX_LAST,SPY US Equity PX_OPEN,SPY US Equity PX_HIGH,SPY US Equity PX_LOW,SPY US Equity PX_VOLUME,SPY US Equity TOT_RETURN_INDEX_GROSS_DVDS
5,2020-01-01 00:00:00,321.86,320.53,322.13,320.15,57106998,321.86
6,2020-01-02 00:00:00,324.87,323.54,324.89,322.53,59253833,324.87
7,2020-01-03 00:00:00,322.41,321.16,323.64,321.1,77783121,322.41
8,2020-01-06 00:00:00,323.64,320.49,323.73,320.36,55761948,323.64
9,2020-01-07 00:00:00,322.73,323.02,323.54,322.24,42854811,322.73

In [149]:
processed = pd.merge(spy,panel,how="inner",on="Dates")

In [150]:
processed.head()

,Dates,SPY US Equity PX_LAST,SPY US Equity PX_OPEN,SPY US Equity PX_HIGH,SPY US Equity PX_LOW,SPY US Equity PX_VOLUME,SPY US Equity TOT_RETURN_INDEX_GROSS_DVDS,XLB US Equity PX_LAST,XLB US Equity PX_OPEN,XLB US Equity PX_HIGH,...,USGG2YR Index PX_OPEN,USGG2YR Index PX_HIGH,USGG2YR Index PX_LOW,USGG2YR Index TOT_RETURN_INDEX_GROSS_DVDS,FDTR Index PX_LAST,FDTR Index TOT_RETURN_INDEX_GROSS_DVDS,CPI YOY Index PX_LAST,CPI YOY Index TOT_RETURN_INDEX_GROSS_DVDS,USURTOT Index PX_LAST,USURTOT Index TOT_RETURN_INDEX_GROSS_DVDS
0,2020-01-02 00:00:00,324.87,323.54,324.89,322.53,59253833,324.87,30.35,30.915,30.97,...,1.565,1.585,1.543,1.569,1.75,1.75,2.3,2.3,3.6,3.6
1,2020-01-03 00:00:00,322.41,321.16,323.64,321.1,77783121,322.41,29.86,30.04,30.22,...,1.5346,1.5527,1.5066,1.5246,1.75,1.75,2.3,2.3,3.6,3.6
2,2020-01-06 00:00:00,323.64,320.49,323.73,320.36,55761948,323.64,29.73,29.775,29.915,...,1.5106,1.5586,1.5086,1.5445,1.75,1.75,2.3,2.3,3.6,3.6
3,2020-01-07 00:00:00,322.73,323.02,323.54,322.24,42854811,322.73,29.695,29.68,29.9,...,1.5425,1.5526,1.5283,1.5404,1.75,1.75,2.3,2.3,3.6,3.6
4,2020-01-08 00:00:00,324.45,322.94,325.78,322.67,68434153,324.45,29.8,29.7,29.92,...,1.4841,1.5826,1.448,1.5806,1.75,1.75,2.3,2.3,3.6,3.6

In [151]:
output_path = folder/"processed"/"data.csv"

In [152]:
processed.to_csv(output_path,index=False)